### ISSUE TITLE
Can not login in multiple question booth - Booth

### ISSUE THREAD

**Issue by jmartinacu** [EGC-23-24/decide-part-lorca#116]
When I tried to vote after creating a multiple question voting. 
I had problems trying to authenticate with the correct username and password of the user that is already added to the census for that specifiec voting.
When I enter the booth page, I get a default authentication form of the browser, which if I fill with the correct data does not work and shows me again the same empty form. If I try to close this form and authenticate using the login of decide, it redirects me to the previous form. 

All of that happened using brave browser, with google chrome is working correctly.

![Image](https://github.com/EGC-23-24/decide-part-lorca/assets/99323099/0b965e50-7d90-4a4f-a936-a8d7cba3402f)

**Comment by goncammej** [comment]
The scenario has been replicated and thoroughly tested on firefox and chromium-based browsers, specifically brave, and on different machines. The problem has not been found, as the authentication is carried out correctly through the means provided by the voting booth view. It seems that the problem is due to the local environment, hence the issue will be closed.
