### ISSUE TITLE
Move project documentation to GitHub Pages - Doc

### ISSUE THREAD

**Issue by alvarobernal2412** [EGC-23-24/decide-part-lorca#329]
It would be nice if all our documentation could be included on the GitHub pages for convenience. I suggest waiting until all documentation is finished.

**Comment by alejandromd** [comment]
The task has been successfully completed. You can view the documentation at: [Documentation-decide-part-lorca](https://egc-23-24.github.io/decide-part-lorca/modules/index.html)

**Comment by alvarobernal2412** [comment]
Finally, due to configuration issues we are unable to add the documentation to the GitHub pages, so this incident will be closed as not planned.

**Comment by alejandromd** [comment]
This issue has been worked on but it has not been possible to find the fault. Due to the few people who are committed to the project in the final stretch of the project, the people who are working have a heavy load of tasks that we can not perform in its entirety. We have to focus on the delivery and I have enough time to correct this error. In my opinion this error could have arisen in a merge omitting some line of the functionality or by the 0004 migration which was deleted at a point in the project and from there the functionality stopped working. 
Add that since the functionality is not well implemented, when setting an automatic end date, the future_stop and end_date attributes are created immediately, which also affects the visualizer by not showing the data view in real time.
That said this issue will be closed as unplanned.
