### ISSUE TITLE
Fix predefined end date - Voting

### ISSUE THREAD

**Issue by alvgonfri** [EGC-23-24/decide-part-lorca#337]
When I create a voting setting a future_stop, the end_date is also set instantly. The end_date must be set only when the future stop is reached.

I have redis an celery running correclty.

![Image](https://github.com/EGC-23-24/decide-part-lorca/assets/73192598/a6e353b0-2aef-48d2-b234-51b13b21bc73)

**Comment by alejandromd** [comment]
This issue has been worked on but it has not been possible to find the fault. Due to the few people who are committed to the project in the final stretch of the project, the people who are working have a heavy load of tasks that we can not perform in its entirety. We have to focus on the delivery and I have enough time to correct this error. In my opinion this error could have arisen in a merge omitting some line of the functionality or by the 0004 migration which was deleted at a point in the project and from there the functionality stopped working. 
Add that since the functionality is not well implemented, when setting an automatic end date, the future_stop and end_date attributes are created immediately, which also affects the visualizer by not showing the data view in real time.
That said this issue will be closed as unplanned.

**Comment by alejandromd** [comment]
The error that caused the asynchronous closing of votes not to work has been located, this problem was in the settings.py file.
This incident is resolve in PR #378
