### ISSUE TITLE
Multiple Questions - Voting

### ISSUE THREAD

**Issue by josgarber6** [EGC-23-24/decide-part-lorca#56]

**Comment by sebasruii** [comment]
This feature allows the creation of a voting with multiple questions. For this, I changed the `Voting` (in voting app) model converting the ManyToOne relationship with `Question` to a ManyToMany relationship. I have also refactored the voting tests and serializers in order to adapt to the new model. All these changes were merged to branch epic/13-several-questions-same-ballot in the pull request #43
